name: style-transfer
channels: !!python/tuple
- !!python/unicode 'anaconda-fusion'
- !!python/unicode 'defaults'
dependencies:
- conda-forge::funcsigs=1.0.2=py27_0
- conda-forge::mock=2.0.0=py27_0
- conda-forge::pbr=1.10.0=py27_0
- conda-forge::protobuf=3.0.0=py27_0
- conda-forge::six=1.10.0=py27_1
- conda-forge::tensorflow=0.11.0=py27_0
- freetype=2.5.5=2
- jbig=2.1=0
- jpeg=9b=0
- libpng=1.6.27=0
- libtiff=4.0.6=3
- mkl=2017.0.1=0
- numpy=1.11.3=py27_0
- openssl=1.0.1k=1
- pillow=4.0.0=py27_0
- pip=9.0.1=py27_1
- python=2.7.9=1
- readline=6.2=2
- scipy=0.18.1=np111py27_1
- setuptools=27.2.0=py27_0
- sqlite=3.13.0=0
- tk=8.5.18=0
- wheel=0.29.0=py27_0
- xz=5.2.2=1
- zlib=1.2.8=3
prefix: /Users/patricia/anaconda2/envs/style-transfer

